name "snow"
version "1.0.0"

recipe "snow::pgm", "PostgreSQL Master"
recipe "snow::pgs", "PostgreSQL Slave"
recipe "snow::api", "API"
recipe "snow::frontend", "Front-end"
recipe "snow::reverse", "Reverse proxy"

depends "postgresql"
depends "nginx"
depends "aws"
depends "postfix"
depends "deploy_wrapper"
depends "ssh_known_hosts"
depends "hostname"
depends "monit"
depends "nodejs"
depends "logrotate"
depends "postfix"
depends "cron"
