#!/bin/sh
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/secrets.sh

REGION=eu-west-1
AZ=${REGION}b
PRIVATE_SUBNET=subnet-8bafe3e0
PUBLIC_SUBNET=subnet-8fafe3e4
AMI="ami-89b1a3fd"
SSH_KEY=/P/Justcoin/Keys/AWS/jc.pem
SSH_KEY_NAME=justcoin
VPC=vpc-vpc-b2afe3d9

PGM_INSTANCE_TYPE=m1.small
PGM_SECURITY_GROUP=sg-fc816993

PGS_INSTANCE_TYPE=m1.small
PGS_SECURITY_GROUP=sg-fb816994

API_INSTANCE_TYPE=t1.micro
API_SECURITY_GROUP=sg-f481699b

WORKERS_INSTANCE_TYPE=t1.micro
WORKERS_SECURITY_GROUP=sg-cd8169a2

FRONTEND_INSTANCE_TYPE=t1.micro
FRONTEND_SECURITY_GROUP=sg-cf8169a0

REVERSE_INSTANCE_TYPE=t1.micro
REVERSE_SECURITY_GROUP=sg-f081699f

ADMIN_INSTANCE_TYPE=t1.micro
ADMIN_SECURITY_GROUP=sg-ce8169a1

LANDING_INSTANCE_TYPE=t1.micro
LANDING_SECURITY_GROUP=sg-50836b3f

APP_INSTANCE_TYPE=m1.small
APP_SECURITY_GROUPS=$API_SECURITY_GROUP,$ADMIN_SECURITY_GROUP,$FRONTEND_SECURITY_GROUP,$LANDING_SECURITY_GROUP,$REVERSE_SECURITY_GROUP

BITCOIND_INSTANCE_TYPE=m1.small
BITCOIND_SECURITY_GROUP=sg-f7816998

LITECOIND_INSTANCE_TYPE=t1.micro
LITECOIND_SECURITY_GROUP=sg-f6816999

export CHEF_SERVER_URL=https://chef.internal.staging.justcoin.com
