#!/bin/sh
REGION=eu-west-1
AZ=${REGION}a
PRIVATE_SUBNET=subnet-9bc6baf0
PUBLIC_SUBNET=subnet-9fc6baf4
AMI="ami-89b1a3fd"
SSH_KEY=/P/Justcoin/Keys/AWS/jc.pem
SSH_KEY_NAME=justcoin
VPC=vpc-81c6baea

PGM_INSTANCE_TYPE=m1.small
PGM_SECURITY_GROUP=sg-3cce2753

PGS_INSTANCE_TYPE=m1.small
PGS_SECURITY_GROUP=sg-bdd43dd2

API_INSTANCE_TYPE=t1.micro
API_SECURITY_GROUP=sg-5dce2732

WORKERS_INSTANCE_TYPE=t1.micro
WORKERS_SECURITY_GROUP=sg-08a24a67

FRONTEND_INSTANCE_TYPE=t1.micro
FRONTEND_SECURITY_GROUP=sg-e01df48f

REVERSE_INSTANCE_TYPE=t1.micro
REVERSE_SECURITY_GROUP=sg-2815fc47

ADMIN_INSTANCE_TYPE=t1.micro
ADMIN_SECURITY_GROUP=sg-e717fe88

LANDING_INSTANCE_TYPE=t1.micro
LANDING_SECURITY_GROUP=sg-ab7a93c4

APP_INSTANCE_TYPE=m1.small
APP_SECURITY_GROUPS=$API_SECURITY_GROUP,$ADMIN_SECURITY_GROUP,$FRONTEND_SECURITY_GROUP,$LANDING_SECURITY_GROUP,$REVERSE_SECURITY_GROUP

BITCOIND_INSTANCE_TYPE=t1.micro
BITCOIND_SECURITY_GROUP=sg-4d4ea722

LITECOIND_INSTANCE_TYPE=t1.micro
LITECOIND_SECURITY_GROUP=sg-294ea746

export CHEF_SERVER_URL=https://chef.internal.justcoin.com
